#!/usr/bin/env python3
"""Generate docs + NB2 prompts for expansion batch 50 furniture."""
from __future__ import annotations

import json
from pathlib import Path

WS = Path(__file__).resolve().parents[1]
PROMPT_DIR = WS / "docs" / "prompt"
CATALOG_MD = WS / "docs" / "furniture_expansion_batch50_catalog.md"
MANIFEST_JSON = WS / "docs" / "furniture_expansion_batch50_manifest.json"

STYLE_PREFIX = (
    "Square game asset 1:1. Single furniture prop centered with generous margin.\n\n"
    "Cute kawaii 2.5D isometric view from upper-left about 45 degrees, hand-painted mobile merge-game "
    "flower shop furniture style. Soft brown outlines slightly thicker than hairline, rounded chibi-friendly "
    "shapes, gentle upper-left lighting, readable silhouette at small grid size."
)

STYLE_SUFFIX = (
    "\n\nNo text, no labels, no numbers, no watermark, no characters, no room shell, no walls, no floor plane.\n\n"
    "Background pure solid white #FFFFFF only for cutout."
)

ITEMS: list[dict] = [
    # ── Set 1: 月辉观蝶套 (butterfly_house) ──
    {
        "id": "bf_moon_lantern_stand",
        "name": "月影落地灯",
        "set": "月辉观蝶套",
        "slot": "light",
        "scene": "butterfly_house",
        "level": 11,
        "cost": 680,
        "star": 3,
        "rarity": "fine",
        "palette": "pale moonstone base, brushed silver stem, frosted lavender glass shade with soft warm glow",
        "subject": "A slim moonlit floor lamp with a crescent-moon finial on top, frosted lilac glass globe shade, elegant butterfly-house observatory mood.",
    },
    {
        "id": "bf_moon_specimen_shelf",
        "name": "月辉标本架",
        "set": "月辉观蝶套",
        "slot": "shelf",
        "scene": "butterfly_house",
        "level": 12,
        "cost": 920,
        "star": 4,
        "rarity": "fine",
        "palette": "warm pale walnut wood, moon-blue trim, tiny brass hooks",
        "subject": "A compact two-tier specimen display shelf with small framed butterfly silhouette slots (abstract shapes only, no readable labels), glass-front lower cubby, airy premium silhouette.",
    },
    {
        "id": "bf_moon_crescent_rug",
        "name": "新月地毯",
        "set": "月辉观蝶套",
        "slot": "ornament",
        "scene": "butterfly_house",
        "level": 12,
        "cost": 760,
        "star": 3,
        "rarity": "fine",
        "palette": "cream and soft lilac woven texture, subtle crescent moon pattern",
        "subject": "A rolled-flat oval area rug prop viewed in isometric top-plus-front angle, soft woven crescent moon motif, plush but low profile, cute floor accent not a whole room.",
    },
    {
        "id": "bf_moon_star_chair",
        "name": "星辉单椅",
        "set": "月辉观蝶套",
        "slot": "ornament",
        "scene": "butterfly_house",
        "level": 13,
        "cost": 880,
        "star": 4,
        "rarity": "fine",
        "palette": "pale wood frame, icy blue upholstery, tiny star embroidery on back cushion",
        "subject": "A single cozy lounge chair with rounded arms, soft star-shaped back cushion detail, compact reading-chair scale for a moonlit butterfly room.",
    },
    {
        "id": "bf_moon_glass_dome",
        "name": "月石玻璃罩",
        "set": "月辉观蝶套",
        "slot": "ornament",
        "scene": "butterfly_house",
        "level": 15,
        "cost": 1280,
        "star": 5,
        "rarity": "rare",
        "palette": "clear glass dome, moon-white marble base, tiny dried branch inside",
        "subject": "A decorative glass cloche dome on a round moonstone pedestal, inside one stylized butterfly wing fragment and a tiny branch, museum display ornament scale.",
    },
    # ── Set 2: 竹影蝶庭套 ──
    {
        "id": "bf_bamboo_low_table",
        "name": "竹编矮几",
        "set": "竹影蝶庭套",
        "slot": "table",
        "scene": "butterfly_house",
        "level": 10,
        "cost": 520,
        "star": 2,
        "rarity": "common",
        "palette": "honey bamboo weave, sage green accent band",
        "subject": "A low square bamboo tea-side table with woven top and chunky rounded legs, compact butterfly-house sitting corner scale.",
    },
    {
        "id": "bf_bamboo_screen",
        "name": "竹纹屏风",
        "set": "竹影蝶庭套",
        "slot": "wallart",
        "scene": "butterfly_house",
        "level": 11,
        "cost": 720,
        "star": 3,
        "rarity": "fine",
        "palette": "natural bamboo slats, soft teal butterfly silhouette inlay",
        "subject": "A folding room divider / screen panel shown as one wall-hanging furniture prop in isometric wall-art angle, three bamboo panels with abstract butterfly cutout motif.",
    },
    {
        "id": "bf_bamboo_hanging_lamp",
        "name": "竹骨吊灯",
        "set": "竹影蝶庭套",
        "slot": "light",
        "scene": "butterfly_house",
        "level": 11,
        "cost": 640,
        "star": 2,
        "rarity": "common",
        "palette": "bamboo ring frame, rice-paper white shade, warm amber glow hint",
        "subject": "A ceiling pendant lamp with bamboo hoop frame and short paper lantern shade, cute toy proportions, hanging chain visible.",
    },
    {
        "id": "bf_bamboo_planter_bench",
        "name": "竹架花凳",
        "set": "竹影蝶庭套",
        "slot": "ornament",
        "scene": "butterfly_house",
        "level": 13,
        "cost": 960,
        "star": 4,
        "rarity": "fine",
        "palette": "bamboo frame, mint cushion, tiny potted wildflowers on one end",
        "subject": "A bench with integrated side planter box, woven bamboo seat, a few cute stylized flowers in the planter, greenhouse reading nook scale.",
    },
    {
        "id": "bf_bamboo_garden_gate",
        "name": "竹艺小门",
        "set": "竹影蝶庭套",
        "slot": "garden",
        "scene": "butterfly_house",
        "level": 14,
        "cost": 1120,
        "star": 4,
        "rarity": "fine",
        "palette": "honey bamboo posts, teal rope accents, tiny butterfly carving",
        "subject": "A small decorative garden gate segment for a butterfly courtyard, rounded bamboo arch top, short width, outdoor-cute not a full fence line.",
    },
    # ── Set 3: 蝶研书房套 ──
    {
        "id": "bf_study_bookcase",
        "name": "观蝶书柜",
        "set": "蝶研书房套",
        "slot": "shelf",
        "scene": "butterfly_house",
        "level": 12,
        "cost": 980,
        "star": 4,
        "rarity": "fine",
        "palette": "warm oak, aqua glass door panels, cream book spines with no text",
        "subject": "A tall narrow bookcase with two glass doors, colorful blank book blocks and one small butterfly field guide shape (cover illustration only, no words).",
    },
    {
        "id": "bf_study_microscope_desk",
        "name": "显微观察台",
        "set": "蝶研书房套",
        "slot": "table",
        "scene": "butterfly_house",
        "level": 13,
        "cost": 1050,
        "star": 4,
        "rarity": "fine",
        "palette": "light wood desk, brass microscope, soft blue notebook stack",
        "subject": "A compact study desk with cute toy microscope, open sketchbook with wing doodles (no readable text), pencil cup, butterfly research mood.",
    },
    {
        "id": "bf_study_pin_board",
        "name": "标本钉板",
        "set": "蝶研书房套",
        "slot": "wallart",
        "scene": "butterfly_house",
        "level": 14,
        "cost": 680,
        "star": 3,
        "rarity": "fine",
        "palette": "cork board, pastel pins, tiny wing silhouette cards",
        "subject": "A wall-mounted cork pin board prop angled for isometric wall art, several abstract butterfly wing cards pinned, ribbon corners, no writing.",
    },
    {
        "id": "bf_study_magnifier_lamp",
        "name": "放大镜台灯",
        "set": "蝶研书房套",
        "slot": "light",
        "scene": "butterfly_house",
        "level": 14,
        "cost": 740,
        "star": 3,
        "rarity": "fine",
        "palette": "brass desk arm, magnifying glass lens shade, warm cream light",
        "subject": "A desk lamp whose shade is a round magnifying glass lens on an adjustable brass arm, scholar corner scale.",
    },
    {
        "id": "bf_study_field_stool",
        "name": "野外折叠凳",
        "set": "蝶研书房套",
        "slot": "ornament",
        "scene": "butterfly_house",
        "level": 16,
        "cost": 860,
        "star": 3,
        "rarity": "fine",
        "palette": "olive canvas seat, light wood X-frame, tiny field bag hanging",
        "subject": "A folded camp stool with small shoulder bag hanging on one side, field researcher accessory for a butterfly house corner.",
    },
    # ── Set 4: 和风茶室套 (tea_house) ──
    {
        "id": "tea_low_chabudai",
        "name": "矮茶桌",
        "set": "和风茶室套",
        "slot": "table",
        "scene": "tea_house",
        "level": 25,
        "cost": 780,
        "star": 4,
        "rarity": "fine",
        "palette": "dark walnut low table, matte black iron corner brackets",
        "subject": "A low Japanese chabudai tea table, square top with subtle wood grain, short sturdy legs, empty except one small tea tray indent, no readable characters.",
    },
    {
        "id": "tea_zabuton_pair",
        "name": "坐垫一对",
        "set": "和风茶室套",
        "slot": "ornament",
        "scene": "tea_house",
        "level": 25,
        "cost": 560,
        "star": 2,
        "rarity": "common",
        "palette": "indigo and cream zabuton cushions, simple geometric weave",
        "subject": "Two floor cushions stacked slightly offset as one ornament group, plump square zabuton shape, subtle traditional pattern without text.",
    },
    {
        "id": "tea_tatami_cabinet",
        "name": "茶道具柜",
        "set": "和风茶室套",
        "slot": "shelf",
        "scene": "tea_house",
        "level": 26,
        "cost": 920,
        "star": 4,
        "rarity": "fine",
        "palette": "charcoal wood cabinet, rice-paper sliding door panels, celadon tea bowls visible",
        "subject": "A low chigai-dana style tea utensil cabinet with two open shelves showing teapot and bowls, sliding shoji panel on lower section, compact footprint.",
    },
    {
        "id": "tea_paper_lantern",
        "name": "和纸行灯",
        "set": "和风茶室套",
        "slot": "light",
        "scene": "tea_house",
        "level": 27,
        "cost": 720,
        "star": 3,
        "rarity": "fine",
        "palette": "bamboo ribs, warm white paper, soft amber glow",
        "subject": "A tall andon floor paper lantern with bamboo lattice skeleton, warm interior glow, tea room mood.",
    },
    {
        "id": "tea_scroll_wall",
        "name": "挂轴墙饰",
        "set": "和风茶室套",
        "slot": "wallart",
        "scene": "tea_house",
        "level": 28,
        "cost": 680,
        "star": 3,
        "rarity": "fine",
        "palette": "cream scroll, ink-wash mountain and cherry branch abstract, dark wood roller",
        "subject": "A hanging scroll kakejiku wall art prop in isometric wall angle, abstract ink landscape and cherry blossom branch, absolutely no calligraphy or readable text.",
    },
    # ── Set 5: 茶庭外观套 ──
    {
        "id": "tea_stone_basin",
        "name": "石水钵",
        "set": "茶庭外观套",
        "slot": "garden",
        "scene": "tea_house",
        "level": 25,
        "cost": 880,
        "star": 4,
        "rarity": "fine",
        "palette": "granite tsukubai basin, moss green accent, bamboo ladle",
        "subject": "A stone water basin tsukubai with short bamboo water spout and wooden ladle resting on rim, zen garden cute scale.",
    },
    {
        "id": "tea_bamboo_fence",
        "name": "竹篱段",
        "set": "茶庭外观套",
        "slot": "garden",
        "scene": "tea_house",
        "level": 26,
        "cost": 760,
        "star": 3,
        "rarity": "fine",
        "palette": "gray-brown bamboo stakes, natural rope bindings",
        "subject": "A short segment of Japanese takegaki bamboo fence, three posts wide, outdoor garden ornament not an endless fence.",
    },
    {
        "id": "tea_maple_bonsai",
        "name": "红枫盆栽",
        "set": "茶庭外观套",
        "slot": "ornament",
        "scene": "tea_house",
        "level": 27,
        "cost": 640,
        "star": 2,
        "rarity": "common",
        "palette": "crimson maple leaves, dark ceramic pot, tiny moss",
        "subject": "A cute stylized Japanese maple bonsai in a round dark pot, autumn red foliage, chibi tree proportions.",
    },
    {
        "id": "tea_stepping_stones",
        "name": "踏石组",
        "set": "茶庭外观套",
        "slot": "garden",
        "scene": "tea_house",
        "level": 28,
        "cost": 980,
        "star": 4,
        "rarity": "fine",
        "palette": "flat gray river stones, subtle moss between",
        "subject": "A cluster of three flat stepping stones arranged as one garden prop group, zen path accent for tea garden.",
    },
    {
        "id": "tea_torii_mini",
        "name": "迷你鸟居",
        "set": "茶庭外观套",
        "slot": "garden",
        "scene": "tea_house",
        "level": 29,
        "cost": 1180,
        "star": 5,
        "rarity": "rare",
        "palette": "vermillion lacquer posts, black lintel, tiny stone base",
        "subject": "A miniature torii gate garden ornament, two posts and top lintels, cute shrine entrance scale for a tea courtyard.",
    },
    # ── Set 6: 法式沙龙套 (garden_villa) ──
    {
        "id": "villa_chester_sofa",
        "name": "切斯特沙发",
        "set": "法式沙龙套",
        "slot": "ornament",
        "scene": "garden_villa",
        "level": 30,
        "cost": 1320,
        "star": 5,
        "rarity": "rare",
        "palette": "dusty rose velvet, dark walnut legs, brass nailhead trim hints",
        "subject": "A compact two-seat chesterfield sofa with deep button tufting, rolled arms, elegant French salon proportions, not oversized.",
    },
    {
        "id": "villa_marble_coffee_table",
        "name": "大理石茶几",
        "set": "法式沙龙套",
        "slot": "table",
        "scene": "garden_villa",
        "level": 30,
        "cost": 980,
        "star": 4,
        "rarity": "fine",
        "palette": "white marble top with soft gray veins, gilt metal legs",
        "subject": "An oval marble coffee table with slim curved gold legs, one rose in a small vase on top, parlor centerpiece scale.",
    },
    {
        "id": "villa_gilded_mirror",
        "name": "镀金壁镜",
        "set": "法式沙龙套",
        "slot": "wallart",
        "scene": "garden_villa",
        "level": 31,
        "cost": 860,
        "star": 3,
        "rarity": "fine",
        "palette": "antique gold rocaille frame, soft reflective glass",
        "subject": "An ornate oval wall mirror prop in isometric wall-art angle, baroque gold frame with small rose garland carving, no reflection scene inside.",
    },
    {
        "id": "villa_crystal_chandelier",
        "name": "水晶吊灯",
        "set": "法式沙龙套",
        "slot": "light",
        "scene": "garden_villa",
        "level": 32,
        "cost": 1180,
        "star": 5,
        "rarity": "rare",
        "palette": "brass frame, clear crystal droplets, warm candle-bulb glow",
        "subject": "A small classic crystal chandelier with two tiers of teardrop prisms, cute simplified proportions for a mobile game room.",
    },
    {
        "id": "villa_rose_armoire",
        "name": "玫瑰衣柜",
        "set": "法式沙龙套",
        "slot": "shelf",
        "scene": "garden_villa",
        "level": 33,
        "cost": 1450,
        "star": 6,
        "rarity": "rare",
        "palette": "cream painted wood, rose gold handles, carved rose crest on top door",
        "subject": "A tall single-door armoire wardrobe with crown molding, rose carving on upper panel, elegant bedroom storage silhouette.",
    },
    # ── Set 7: 玫瑰阳台套 ──
    {
        "id": "villa_wrought_bench",
        "name": "铁艺长椅",
        "set": "玫瑰阳台套",
        "slot": "garden",
        "scene": "garden_villa",
        "level": 31,
        "cost": 920,
        "star": 4,
        "rarity": "fine",
        "palette": "black wrought iron scrolls, pale pink seat cushion",
        "subject": "A garden bench with ornate iron armrest curls and soft cushion, Paris balcony mood, outdoor cute scale.",
    },
    {
        "id": "villa_planter_urn",
        "name": "古典花瓮",
        "set": "玫瑰阳台套",
        "slot": "garden",
        "scene": "garden_villa",
        "level": 32,
        "cost": 780,
        "star": 3,
        "rarity": "fine",
        "palette": "terracotta urn, blush roses overflowing",
        "subject": "A tall classical planter urn with fluted sides, abundant cute stylized pink roses, villa terrace accent.",
    },
    {
        "id": "villa_balcony_table",
        "name": "阳台小圆桌",
        "set": "玫瑰阳台套",
        "slot": "table",
        "scene": "garden_villa",
        "level": 33,
        "cost": 680,
        "star": 3,
        "rarity": "fine",
        "palette": "white wrought iron table, mint tea cup pair",
        "subject": "A small round bistro table for a balcony, thin metal legs, two teacups and a tiny rose bud vase on top.",
    },
    {
        "id": "villa_parasol_stand",
        "name": "阳伞架",
        "set": "玫瑰阳台套",
        "slot": "ornament",
        "scene": "garden_villa",
        "level": 34,
        "cost": 720,
        "star": 3,
        "rarity": "fine",
        "palette": "striped cream and rose parasol, iron stand base",
        "subject": "A folded patio parasol inserted into a weighted stand, striped fabric, terrace shade ornament.",
    },
    {
        "id": "villa_rose_trellis",
        "name": "玫瑰爬架",
        "set": "玫瑰阳台套",
        "slot": "garden",
        "scene": "garden_villa",
        "level": 35,
        "cost": 1280,
        "star": 5,
        "rarity": "rare",
        "palette": "white painted lattice, climbing pink roses",
        "subject": "A short arched rose trellis segment with climbing flowers, garden entry accent, not a full wall.",
    },
    # ── Set 8: 树屋卧眠套 (forest_treehouse) ──
    {
        "id": "tree_canopy_bed",
        "name": "树冠小床",
        "set": "树屋卧眠套",
        "slot": "ornament",
        "scene": "forest_treehouse",
        "level": 35,
        "cost": 1380,
        "star": 6,
        "rarity": "rare",
        "palette": "curved oak headboard like a branch, moss green blanket, cream pillow",
        "subject": "A cozy single canopy bed with wooden branch-shaped headboard, leaf motif quilt, fairy treehouse bedroom scale, foot visible in isometric view.",
    },
    {
        "id": "tree_nightstand",
        "name": "树洞床头柜",
        "set": "树屋卧眠套",
        "slot": "table",
        "scene": "forest_treehouse",
        "level": 36,
        "cost": 720,
        "star": 3,
        "rarity": "fine",
        "palette": "hollow log body, bark texture, tiny acorn lamp on top",
        "subject": "A nightstand carved from a hollow tree stump with one small drawer, acorn-shaped lamp and closed book on top, no readable text.",
    },
    {
        "id": "tree_wardrobe_round",
        "name": "圆顶衣柜",
        "set": "树屋卧眠套",
        "slot": "shelf",
        "scene": "forest_treehouse",
        "level": 37,
        "cost": 1120,
        "star": 5,
        "rarity": "rare",
        "palette": "warm oak barrel shape, mushroom knob handles, leaf carvings",
        "subject": "A round mushroom-cap topped wardrobe cabinet, wooden staves, fairy forest carpentry, storage furniture scale.",
    },
    {
        "id": "tree_moon_window",
        "name": "圆窗墙饰",
        "set": "树屋卧眠套",
        "slot": "wallart",
        "scene": "forest_treehouse",
        "level": 37,
        "cost": 640,
        "star": 2,
        "rarity": "common",
        "palette": "round porthole window frame, night sky blue glass, tiny star stickers",
        "subject": "A circular treehouse window wall prop in isometric wall angle, wooden frame built into trunk shape, starry glass pane, no landscape detail outside.",
    },
    {
        "id": "tree_star_lamp",
        "name": "星点吊灯",
        "set": "树屋卧眠套",
        "slot": "light",
        "scene": "forest_treehouse",
        "level": 38,
        "cost": 860,
        "star": 4,
        "rarity": "fine",
        "palette": "twig frame, glowing star charms, warm fairy light",
        "subject": "A hanging pendant lamp made of woven twigs with five tiny glowing star ornaments, enchanted treehouse bedroom light.",
    },
    # ── Set 9: 橡树客厅套 ──
    {
        "id": "tree_hammock_chair",
        "name": "吊篮椅",
        "set": "橡树客厅套",
        "slot": "ornament",
        "scene": "forest_treehouse",
        "level": 35,
        "cost": 980,
        "star": 4,
        "rarity": "fine",
        "palette": "woven rope basket chair, sage cushion, oak spreader bar",
        "subject": "A hanging egg-chair / hammock chair with rope net and plush cushion, suspended from a short visible hook bar, cozy nook seating.",
    },
    {
        "id": "tree_stump_table",
        "name": "木桩茶几",
        "set": "橡树客厅套",
        "slot": "table",
        "scene": "forest_treehouse",
        "level": 36,
        "cost": 760,
        "star": 3,
        "rarity": "fine",
        "palette": "cross-section stump top, bark sides, tiny teapot",
        "subject": "A coffee table made from a tree stump slice, natural bark edge, small ceramic teapot and two cups on top.",
    },
    {
        "id": "tree_bookshelf_hollow",
        "name": "空心树书架",
        "set": "橡树客厅套",
        "slot": "shelf",
        "scene": "forest_treehouse",
        "level": 37,
        "cost": 1050,
        "star": 4,
        "rarity": "fine",
        "palette": "hollow trunk shelves, moss trim, colorful blank books",
        "subject": "A bookshelf built inside a hollow oak trunk with three shelf levels, mossy edges, blank colorful book blocks and one tiny owl figurine.",
    },
    {
        "id": "tree_mushroom_lamp",
        "name": "蘑菇落地灯",
        "set": "橡树客厅套",
        "slot": "light",
        "scene": "forest_treehouse",
        "level": 38,
        "cost": 820,
        "star": 4,
        "rarity": "fine",
        "palette": "red spotted mushroom cap shade, cream stem stand, soft glow",
        "subject": "A floor lamp shaped like a large cute toadstool mushroom, warm light from cap underside, forest fairy mood.",
    },
    {
        "id": "tree_rope_ladder_shelf",
        "name": "绳梯展示架",
        "set": "橡树客厅套",
        "slot": "ornament",
        "scene": "forest_treehouse",
        "level": 39,
        "cost": 1180,
        "star": 5,
        "rarity": "rare",
        "palette": "rope ladder with three tiny wooden platforms, hanging jars",
        "subject": "A vertical rope ladder shelf with three small platforms holding jars and a tiny potted fern, treehouse wall accent ornament.",
    },
    # ── Set 10: 跨场景限定单件 ──
    {
        "id": "bf_aurora_terrarium",
        "name": "极光生态箱",
        "set": "跨场景限定",
        "slot": "shelf",
        "scene": "butterfly_house",
        "level": 18,
        "cost": 1580,
        "star": 6,
        "rarity": "limited",
        "palette": "black metal frame, aurora gradient glass, tiny glowing plants inside",
        "subject": "A premium rectangular terrarium cabinet with aurora-colored glass panels, bioluminescent cute plants and one butterfly silhouette inside, limited collector piece.",
    },
    {
        "id": "tea_gold_koi_pond",
        "name": "金鲤庭园池",
        "set": "跨场景限定",
        "slot": "garden",
        "scene": "tea_house",
        "level": 28,
        "cost": 1420,
        "star": 5,
        "rarity": "limited",
        "palette": "stone-edged pond, gold and orange koi shapes, lily pad",
        "subject": "A small square ornamental koi pond garden prop, two cute stylized koi fish, one lily pad, stone rim, water surface simplified.",
    },
    {
        "id": "villa_grand_piano",
        "name": "三角钢琴",
        "set": "跨场景限定",
        "slot": "ornament",
        "scene": "garden_villa",
        "level": 34,
        "cost": 1680,
        "star": 6,
        "rarity": "limited",
        "palette": "glossy black piano body, brass pedals, open lid",
        "subject": "A grand piano side view in isometric angle, lid propped open, elegant villa parlor centerpiece, keys visible but no brand text.",
    },
    {
        "id": "tree_fairy_door",
        "name": "精灵小门",
        "set": "跨场景限定",
        "slot": "wallart",
        "scene": "forest_treehouse",
        "level": 36,
        "cost": 920,
        "star": 4,
        "rarity": "fine",
        "palette": "tiny arched green door, copper hinges, glow crack at frame",
        "subject": "A miniature fairy door wall prop embedded in bark-textured frame, round window hole, magical forest wall accent in isometric wall angle.",
    },
    {
        "id": "exp50_world_globe_bar",
        "name": "地球仪酒柜",
        "set": "跨场景限定",
        "slot": "shelf",
        "scene": "garden_villa",
        "level": 40,
        "cost": 1850,
        "star": 7,
        "rarity": "limited",
        "palette": "walnut bar cabinet, large vintage globe on top, brass trim",
        "subject": "A compact globe-topped drinks cabinet with globe sphere on upper section and small bottle silhouettes behind glass door below, explorer salon mood, no labels.",
    },
]

RARITY_CN = {
    "common": "普通",
    "fine": "精良",
    "rare": "稀有",
    "limited": "限定",
}

SLOT_CN = {
    "shelf": "花架",
    "table": "桌台",
    "light": "家电",
    "ornament": "摆件",
    "wallart": "墙饰",
    "garden": "庭院",
}

SCENE_CN = {
    "butterfly_house": "蝴蝶小屋",
    "tea_house": "茶香小院",
    "garden_villa": "花园别墅",
    "forest_treehouse": "橡树小屋",
}


def build_prompt(item: dict) -> str:
    return (
        f"{STYLE_PREFIX}\n\n"
        f"Color and materials: {item['palette']}.\n\n"
        f"Subject: {item['subject']}\n"
        f"{STYLE_SUFFIX}"
    )


def write_catalog() -> None:
    lines = [
        "# 扩展家具批次 50 — 策划表",
        "",
        "适用场景：蝴蝶小屋及后续 **茶香小院 / 花园别墅 / 橡树小屋**（房壳尚未全部开放，家具先储备）。",
        "",
        "经济：花愿售价刻意压低（约 520–1850），星星 2–7；**未写入 DecorationConfig**，待抠图验收后再登记。",
        "",
        "出图：`scripts/gen_furniture_expansion_batch50_nb2.sh` → raw 落 `../game_assets/huahua/assets/raw/`。",
        "",
        "## 套装一览（10 套 × 5 件）",
        "",
    ]
    sets: dict[str, list[dict]] = {}
    for it in ITEMS:
        sets.setdefault(it["set"], []).append(it)

    for set_name, members in sets.items():
        lines.append(f"### {set_name}")
        lines.append("")
        lines.append("| id | 名称 | 槽位 | 场景 | 等级 | 花愿 | 星星 | 稀有度 |")
        lines.append("|---|---|---|---|---:|---:|---:|---|")
        for it in members:
            lines.append(
                f"| `{it['id']}` | {it['name']} | {SLOT_CN[it['slot']]} | {SCENE_CN[it['scene']]} | "
                f"{it['level']} | {it['cost']} | {it['star']} | {RARITY_CN[it['rarity']]} |"
            )
        lines.append("")

    lines.append("## 汇总")
    lines.append("")
    lines.append(f"- 合计：**{len(ITEMS)}** 件")
    lines.append(f"- 花愿区间：**{min(i['cost'] for i in ITEMS)} – {max(i['cost'] for i in ITEMS)}**")
    lines.append(f"- 等级区间：**{min(i['level'] for i in ITEMS)} – {max(i['level'] for i in ITEMS)}**")
    lines.append("")

    CATALOG_MD.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    assert len(ITEMS) == 50, f"expected 50 items, got {len(ITEMS)}"
    PROMPT_DIR.mkdir(parents=True, exist_ok=True)
    for it in ITEMS:
        path = PROMPT_DIR / f"furniture_{it['id']}_nb2_prompt.txt"
        path.write_text(build_prompt(it), encoding="utf-8")
    MANIFEST_JSON.write_text(json.dumps(ITEMS, ensure_ascii=False, indent=2), encoding="utf-8")
    write_catalog()
    print(f"Wrote {len(ITEMS)} prompts to {PROMPT_DIR}")
    print(f"Catalog: {CATALOG_MD}")
    print(f"Manifest: {MANIFEST_JSON}")


if __name__ == "__main__":
    main()
