#!/usr/bin/env python3
"""Generate docs + NB2 prompts for expansion batch 51 (creative + ancient Chinese)."""
from __future__ import annotations

import json
from pathlib import Path

WS = Path(__file__).resolve().parents[1]
PROMPT_DIR = WS / "docs" / "prompt"
CATALOG_MD = WS / "docs" / "furniture_expansion_batch51_catalog.md"
MANIFEST_JSON = WS / "docs" / "furniture_expansion_batch51_manifest.json"

STYLE_PREFIX = (
    "Square game asset 1:1. Single furniture prop centered with generous margin.\n\n"
    "Cute kawaii 2.5D isometric view from upper-left about 45 degrees, hand-painted mobile merge-game "
    "flower shop furniture style. Soft brown outlines slightly thicker than hairline, rounded chibi-friendly "
    "shapes, gentle upper-left lighting, readable silhouette at small grid size."
)

STYLE_SUFFIX = (
    "\n\nNo text, no labels, no numbers, no watermark, no characters, no room shell, no walls, no floor plane. "
    "No ceiling-hanging lamp, no pendant light, no chandelier, no chain-suspended light fixture.\n\n"
    "Background pure solid white #FFFFFF only for cutout."
)

ITEMS: list[dict] = [
    # ── Set 1: 文房四宝套 ──
    {
        "id": "ancient_inkstone_desk",
        "name": "砚台书案",
        "set": "文房四宝套",
        "slot": "table",
        "scene": "tea_house",
        "level": 14,
        "cost": 820,
        "star": 3,
        "rarity": "fine",
        "palette": "dark rosewood desk, black inkstone slab, celadon water dropper, bamboo brush rest",
        "subject": "A low Chinese scholar writing desk with recessed inkstone, water dropper, and brush rest, elegant literati study mood, compact game prop scale.",
    },
    {
        "id": "ancient_brush_mountain",
        "name": "笔架山",
        "set": "文房四宝套",
        "slot": "ornament",
        "scene": "tea_house",
        "level": 14,
        "cost": 580,
        "star": 2,
        "rarity": "common",
        "palette": "carved mountain-shaped brush holder, pale jade green glaze, tiny brush silhouettes",
        "subject": "A miniature mountain-shaped brush holder with several calligraphy brushes standing upright, scholar desk ornament, no readable characters on brushes.",
    },
    {
        "id": "ancient_scroll_rack",
        "name": "经卷竹架",
        "set": "文房四宝套",
        "slot": "shelf",
        "scene": "tea_house",
        "level": 15,
        "cost": 940,
        "star": 4,
        "rarity": "fine",
        "palette": "bamboo scroll storage rack, cream rolled scrolls with blank ends, red cord ties",
        "subject": "A vertical bamboo rack holding several rolled scrolls tied with red cord, blank paper ends only, no calligraphy text.",
    },
    {
        "id": "ancient_scholar_rock",
        "name": "太湖赏石",
        "set": "文房四宝套",
        "slot": "ornament",
        "scene": "tea_house",
        "level": 16,
        "cost": 720,
        "star": 3,
        "rarity": "fine",
        "palette": "gray porous Taihu rock on carved wooden stand, moss speck hints",
        "subject": "A single scholar's viewing rock taihu stone on a low carved wooden pedestal, elegant perforated silhouette, garden-indoor ornament scale.",
    },
    {
        "id": "ancient_guqin_table",
        "name": "古琴案",
        "set": "文房四宝套",
        "slot": "table",
        "scene": "tea_house",
        "level": 17,
        "cost": 1080,
        "star": 4,
        "rarity": "fine",
        "palette": "warm lacquer low table, guqin zither on top, silk tassel hint",
        "subject": "A low Chinese table with a guqin zither resting on top, seven-string silhouette readable, refined music corner prop.",
    },
    # ── Set 2: 罗帐闺阁套 ──
    {
        "id": "ancient_canopy_bed",
        "name": "架子床",
        "set": "罗帐闺阁套",
        "slot": "ornament",
        "scene": "garden_villa",
        "level": 28,
        "cost": 1420,
        "star": 5,
        "rarity": "rare",
        "palette": "red lacquer bed frame, translucent silk canopy curtains, gold corner carvings",
        "subject": "A traditional Chinese canopy bed with four posts and draped translucent curtains, carved headboard, cozy ancient bedroom centerpiece in isometric view.",
    },
    {
        "id": "ancient_lacquer_wardrobe",
        "name": "漆彩衣柜",
        "set": "罗帐闺阁套",
        "slot": "shelf",
        "scene": "garden_villa",
        "level": 29,
        "cost": 1180,
        "star": 5,
        "rarity": "rare",
        "palette": "cinnabar red lacquer wardrobe, gold peony motifs, black brass hardware",
        "subject": "A tall two-door Chinese lacquer wardrobe with peony and vine gold painting, rounded chibi-friendly proportions.",
    },
    {
        "id": "ancient_dressing_case",
        "name": "梳妆奁台",
        "set": "罗帐闺阁套",
        "slot": "table",
        "scene": "garden_villa",
        "level": 28,
        "cost": 860,
        "star": 3,
        "rarity": "fine",
        "palette": "black lacquer dressing table, bronze mirror on stand, jade hairpin tray",
        "subject": "A vanity dressing table with folding bronze mirror, small jewelry tray, and hairpin box, ancient boudoir mood, no face in mirror.",
    },
    {
        "id": "ancient_landscape_screen",
        "name": "山水屏风",
        "set": "罗帐闺阁套",
        "slot": "wallart",
        "scene": "garden_villa",
        "level": 30,
        "cost": 980,
        "star": 4,
        "rarity": "fine",
        "palette": "ink-wash mountain panels on folding screen, ebony frame",
        "subject": "A four-panel folding screen shown as one wall-art prop in isometric wall angle, ink landscape painting on each panel, absolutely no calligraphy.",
    },
    {
        "id": "ancient_medicine_chest",
        "name": "百子药柜",
        "set": "罗帐闺阁套",
        "slot": "shelf",
        "scene": "garden_villa",
        "level": 31,
        "cost": 1050,
        "star": 4,
        "rarity": "fine",
        "palette": "many small drawer apothecary chest, warm honey wood, brass pull rings",
        "subject": "A traditional Chinese medicine cabinet with grid of tiny drawers and brass ring pulls, cute apothecary silhouette, no labels on drawers.",
    },
    # ── Set 3: 宫廷陈设套 ──
    {
        "id": "ancient_luohan_daybed",
        "name": "罗汉床",
        "set": "宫廷陈设套",
        "slot": "ornament",
        "scene": "garden_villa",
        "level": 32,
        "cost": 1350,
        "star": 5,
        "rarity": "rare",
        "palette": "huanghuali wood daybed, woven rattan seat, jade pillow",
        "subject": "A Chinese luohan daybed couch with waist-high rails on three sides, rattan mat surface, small side table attached, palace lounge seating.",
    },
    {
        "id": "ancient_bronze_ding",
        "name": "三足鼎案",
        "set": "宫廷陈设套",
        "slot": "ornament",
        "scene": "garden_villa",
        "level": 33,
        "cost": 1280,
        "star": 5,
        "rarity": "rare",
        "palette": "patina bronze ding tripod vessel on low stand, cloud pattern relief",
        "subject": "A ceremonial bronze ding tripod cauldron on a low display stand, green-brown patina, stylized taotie motifs, museum centerpiece scale.",
    },
    {
        "id": "ancient_master_chair",
        "name": "太师椅",
        "set": "宫廷陈设套",
        "slot": "ornament",
        "scene": "garden_villa",
        "level": 32,
        "cost": 920,
        "star": 4,
        "rarity": "fine",
        "palette": "dark hardwood armchair, rectangular back splat with dragon carving",
        "subject": "A single grand master armchair yoke-back chair with carved dragon on back splat, formal court seating, sturdy silhouette.",
    },
    {
        "id": "ancient_jade_bi_stand",
        "name": "礼璧展架",
        "set": "宫廷陈设套",
        "slot": "shelf",
        "scene": "garden_villa",
        "level": 34,
        "cost": 1120,
        "star": 4,
        "rarity": "fine",
        "palette": "black wood display stand, large pale green jade bi disc, red silk pad",
        "subject": "A display shelf holding one large jade bi disc ring on a red silk pad, ceremonial artifact presentation, compact footprint.",
    },
    {
        "id": "ancient_phoenix_rug",
        "name": "凤纹地毯",
        "set": "宫廷陈设套",
        "slot": "ornament",
        "scene": "garden_villa",
        "level": 33,
        "cost": 780,
        "star": 3,
        "rarity": "fine",
        "palette": "deep red woven rug, gold phoenix motif, teal border",
        "subject": "A flat rectangular palace rug prop viewed in isometric top-plus-front angle, stylized phoenix embroidery pattern, low profile floor accent.",
    },
    # ── Set 4: 江南水巷套 ──
    {
        "id": "jiangnan_blue_cabinet",
        "name": "青花博古柜",
        "set": "江南水巷套",
        "slot": "shelf",
        "scene": "tea_house",
        "level": 24,
        "cost": 1020,
        "star": 4,
        "rarity": "fine",
        "palette": "white and cobalt blue porcelain vases on open rosewood shelves",
        "subject": "A display cabinet with open shelves showing blue-and-white porcelain vases and bowls, Jiangnan water-town collector mood.",
    },
    {
        "id": "jiangnan_wash_bench",
        "name": "临河浣衣凳",
        "set": "江南水巷套",
        "slot": "ornament",
        "scene": "tea_house",
        "level": 24,
        "cost": 620,
        "star": 2,
        "rarity": "common",
        "palette": "weathered gray wood bench, woven basket underneath, white cloth fold",
        "subject": "A rustic riverside washing bench with a wicker basket below and folded white cloth on seat, humble Jiangnan daily life prop.",
    },
    {
        "id": "jiangnan_lattice_window",
        "name": "花窗栏",
        "set": "江南水巷套",
        "slot": "wallart",
        "scene": "tea_house",
        "level": 25,
        "cost": 740,
        "star": 3,
        "rarity": "fine",
        "palette": "white plaster frame, geometric ice-ray lattice, pale blue sky glass hint",
        "subject": "A decorative Chinese window lattice wall panel in isometric wall-art angle, ice-ray geometric pattern, no scene visible through window.",
    },
    {
        "id": "jiangnan_rattan_daybed",
        "name": "藤枕榻",
        "set": "江南水巷套",
        "slot": "ornament",
        "scene": "tea_house",
        "level": 26,
        "cost": 980,
        "star": 4,
        "rarity": "fine",
        "palette": "bamboo daybed frame, indigo cotton cushion, white porcelain pillow",
        "subject": "A Jiangnan daybed couch with bamboo frame and indigo cushion, low lounge for afternoon nap, open side silhouette.",
    },
    {
        "id": "jiangnan_willow_cart",
        "name": "柳编花车",
        "set": "江南水巷套",
        "slot": "garden",
        "scene": "tea_house",
        "level": 27,
        "cost": 880,
        "star": 4,
        "rarity": "fine",
        "palette": "willow-woven cart, wooden wheels, peony and lotus buckets",
        "subject": "A small flower vendor cart with wicker body, two wooden wheels, buckets of cute stylized peonies, outdoor garden prop.",
    },
    # ── Set 5: 私家园林套 ──
    {
        "id": "ancient_moon_gate",
        "name": "月洞门",
        "set": "私家园林套",
        "slot": "garden",
        "scene": "tea_house",
        "level": 26,
        "cost": 1150,
        "star": 4,
        "rarity": "fine",
        "palette": "white plaster moon gate arch, gray tile coping, moss base stones",
        "subject": "A circular moon gate garden portal segment, short freestanding wall section with round opening, classical Chinese garden entry accent.",
    },
    {
        "id": "ancient_stone_lantern",
        "name": "石灯笼",
        "set": "私家园林套",
        "slot": "garden",
        "scene": "tea_house",
        "level": 25,
        "cost": 680,
        "star": 3,
        "rarity": "fine",
        "palette": "granite stone lantern on pedestal, warm candle glow inside chamber",
        "subject": "A ground-standing Japanese-Chinese stone lantern ishi-doro on a pedestal base, square light chamber with warm glow, NOT hanging, firmly on ground.",
    },
    {
        "id": "ancient_pavilion_stool",
        "name": "亭畔石凳",
        "set": "私家园林套",
        "slot": "garden",
        "scene": "tea_house",
        "level": 26,
        "cost": 560,
        "star": 2,
        "rarity": "common",
        "palette": "gray stone drum stools pair, tiny hex pavilion roof fragment behind as backrest hint",
        "subject": "Two round stone drum stools as one garden prop group, subtle tiny pavilion roof corner behind them, outdoor rest spot scale.",
    },
    {
        "id": "ancient_lion_pair",
        "name": "对狮守院",
        "set": "私家园林套",
        "slot": "garden",
        "scene": "tea_house",
        "level": 28,
        "cost": 1220,
        "star": 5,
        "rarity": "rare",
        "palette": "weathered stone guardian lions, one paw on ball, marble gray",
        "subject": "A pair of Chinese guardian lion statues on one shared low plinth, cute stylized shishi, garden gate guardians not oversized.",
    },
    {
        "id": "ancient_jade_bridge",
        "name": "弧桥渡月",
        "set": "私家园林套",
        "slot": "garden",
        "scene": "tea_house",
        "level": 29,
        "cost": 1380,
        "star": 5,
        "rarity": "rare",
        "palette": "pale jade-green stone arch bridge segment, ripple water suggestion at base",
        "subject": "A short single-arch garden bridge segment for a pond crossing, curved stone steps, simplified water ripple at base edge only.",
    },
    # ── Set 6: 丹房仙侠套 ──
    {
        "id": "xianxia_alchemy_furnace",
        "name": "八卦丹炉",
        "set": "丹房仙侠套",
        "slot": "ornament",
        "scene": "forest_treehouse",
        "level": 36,
        "cost": 1480,
        "star": 6,
        "rarity": "rare",
        "palette": "bronze tripod furnace, bagua symbols as abstract patterns, faint cyan smoke wisps",
        "subject": "A cute xianxia alchemy furnace on three legs with dome lid, bagua trigram patterns as abstract shapes not readable text, gentle smoke curl.",
    },
    {
        "id": "xianxia_herb_rack",
        "name": "悬索晒药架",
        "set": "丹房仙侠套",
        "slot": "shelf",
        "scene": "forest_treehouse",
        "level": 36,
        "cost": 920,
        "star": 4,
        "rarity": "fine",
        "palette": "bamboo frame drying rack, hanging herb bundles, paper packets",
        "subject": "A horizontal herb drying rack on wooden posts with strings of dried plants and paper packets hanging below, apothecary shelf not a light fixture.",
    },
    {
        "id": "xianxia_gourd_shelf",
        "name": "葫芦药瓶架",
        "set": "丹房仙侠套",
        "slot": "shelf",
        "scene": "forest_treehouse",
        "level": 37,
        "cost": 860,
        "star": 3,
        "rarity": "fine",
        "palette": "dark wood shelf, gourd-shaped bottles, cork stoppers, amber liquids",
        "subject": "A narrow shelf lined with gourd-shaped medicine bottles and one small mortar, Taoist pharmacy mood.",
    },
    {
        "id": "xianxia_meditation_platform",
        "name": "蒲团云台",
        "set": "丹房仙侠套",
        "slot": "table",
        "scene": "forest_treehouse",
        "level": 38,
        "cost": 780,
        "star": 3,
        "rarity": "fine",
        "palette": "floating cloud-pattern low platform, round rush mat cushion on top",
        "subject": "A low meditation platform table with round rush cushion zafu on top, subtle cloud carving on platform edges, fairy cultivation corner.",
    },
    {
        "id": "xianxia_peach_stand",
        "name": "仙桃祭台",
        "set": "丹房仙侠套",
        "slot": "ornament",
        "scene": "forest_treehouse",
        "level": 39,
        "cost": 1180,
        "star": 5,
        "rarity": "rare",
        "palette": "peach wood altar table, glowing peach fruit, talisman paper strips without text",
        "subject": "A small peach wood offering stand with one glowing peach and blank yellow paper talisman strips, no readable characters, mystical forest shrine.",
    },
    # ── Set 7: 节庆民间套 ──
    {
        "id": "folk_lion_head_stand",
        "name": "醒狮头架",
        "set": "节庆民间套",
        "slot": "ornament",
        "scene": "flower_shop",
        "level": 12,
        "cost": 880,
        "star": 4,
        "rarity": "fine",
        "palette": "colorful lion dance head on stand, gold foil, red silk, big cute eyes",
        "subject": "A festive lion dance head mounted on a display stand, bold red and gold, fluffy trim, celebration shop ornament.",
    },
    {
        "id": "folk_dragon_bench",
        "name": "龙纹长凳",
        "set": "节庆民间套",
        "slot": "ornament",
        "scene": "flower_shop",
        "level": 13,
        "cost": 760,
        "star": 3,
        "rarity": "fine",
        "palette": "red lacquer bench, carved dragon rail, yellow cushion",
        "subject": "A long festival bench with dragon carving along the back rail, bright celebratory colors, parade viewing seat scale.",
    },
    {
        "id": "folk_kite_wall",
        "name": "沙燕风筝墙",
        "set": "节庆民间套",
        "slot": "wallart",
        "scene": "flower_shop",
        "level": 14,
        "cost": 640,
        "star": 2,
        "rarity": "common",
        "palette": "swallow-shaped kites in red and cyan, bamboo frame wall mount",
        "subject": "Three traditional swallow kites mounted as one wall-art group in isometric wall angle, bright folk craft patterns, no text.",
    },
    {
        "id": "folk_drum_table",
        "name": "羯鼓茶几",
        "set": "节庆民间套",
        "slot": "table",
        "scene": "flower_shop",
        "level": 15,
        "cost": 820,
        "star": 3,
        "rarity": "fine",
        "palette": "waist-drums as table legs supporting round top, red lacquer, gold rims",
        "subject": "A whimsical round tea table supported by three small waist drums as legs, festive folk craft furniture, teacups on top.",
    },
    {
        "id": "folk_pole_lantern",
        "name": "灯杆宫灯",
        "set": "节庆民间套",
        "slot": "garden",
        "scene": "flower_shop",
        "level": 16,
        "cost": 720,
        "star": 3,
        "rarity": "fine",
        "palette": "red palace lantern on tall wooden pole with crossbar, ground base stone",
        "subject": "A festival palace lantern mounted on a vertical wooden pole standing on stone base, ground-standing street lantern, absolutely NOT ceiling-hung.",
    },
    # ── Set 8: 海贸奇珍套 ──
    {
        "id": "sea_treasure_chest",
        "name": "航海宝箱",
        "set": "海贸奇珍套",
        "slot": "ornament",
        "scene": "garden_villa",
        "level": 31,
        "cost": 980,
        "star": 4,
        "rarity": "fine",
        "palette": "weathered oak chest, iron bands, pearls and coral spilling slightly",
        "subject": "An open treasure chest with pearls, coral branch, and compass spilling out, maritime collector ornament.",
    },
    {
        "id": "sea_coral_cabinet",
        "name": "珊瑚玻璃柜",
        "set": "海贸奇珍套",
        "slot": "shelf",
        "scene": "garden_villa",
        "level": 32,
        "cost": 1150,
        "star": 4,
        "rarity": "fine",
        "palette": "teak cabinet with glass doors, pink coral branches, conch shells inside",
        "subject": "A display cabinet with glass doors showcasing coral branches and seashells, coastal curiosity cabinet mood.",
    },
    {
        "id": "sea_compass_desk",
        "name": "罗盘航海桌",
        "set": "海贸奇珍套",
        "slot": "table",
        "scene": "garden_villa",
        "level": 33,
        "cost": 890,
        "star": 3,
        "rarity": "fine",
        "palette": "captain desk, brass compass, rolled blank charts, rope coil",
        "subject": "A captain navigation desk with large brass compass, rolled blank maps, and rope coil, no readable map text.",
    },
    {
        "id": "sea_anchor_bench",
        "name": "船锚长椅",
        "set": "海贸奇珍套",
        "slot": "garden",
        "scene": "garden_villa",
        "level": 34,
        "cost": 840,
        "star": 3,
        "rarity": "fine",
        "palette": "rusty ship anchor as bench back, teak seat plank, rope wrap",
        "subject": "A garden bench creatively built around a ship anchor as the backrest, nautical patio seating for villa terrace.",
    },
    {
        "id": "sea_wheel_wall",
        "name": "舵轮墙饰",
        "set": "海贸奇珍套",
        "slot": "wallart",
        "scene": "garden_villa",
        "level": 34,
        "cost": 700,
        "star": 3,
        "rarity": "fine",
        "palette": "wooden ship wheel, brass hub, rope hanger on wall",
        "subject": "A ship steering wheel mounted as wall decor in isometric wall-art angle, nautical trophy piece.",
    },
    # ── Set 9: 奇匠造物套 ──
    {
        "id": "whimsy_clockwork_shelf",
        "name": "发条花格架",
        "set": "奇匠造物套",
        "slot": "shelf",
        "scene": "butterfly_house",
        "level": 17,
        "cost": 1120,
        "star": 4,
        "rarity": "fine",
        "palette": "brass gears visible in frame, wood shelves, tiny clockwork flower pots",
        "subject": "A shelf unit with exposed brass clockwork gears in the sides, small pots with mechanical flower buds that look ready to bloom.",
    },
    {
        "id": "whimsy_armillary_desk",
        "name": "浑天仪案",
        "set": "奇匠造物套",
        "slot": "table",
        "scene": "butterfly_house",
        "level": 18,
        "cost": 1240,
        "star": 5,
        "rarity": "rare",
        "palette": "bronze armillary sphere on desk, star chart inlay, dark wood base",
        "subject": "A scholar desk with a cute armillary sphere astrolabe as centerpiece, rings and globe readable, steampunk-observatory crossover.",
    },
    {
        "id": "whimsy_snail_sofa",
        "name": "蜗壳沙发",
        "set": "奇匠造物套",
        "slot": "ornament",
        "scene": "butterfly_house",
        "level": 19,
        "cost": 1320,
        "star": 5,
        "rarity": "rare",
        "palette": "spiral snail shell backrest in pearlescent pink, moss green cushion seat",
        "subject": "A whimsical single-seat sofa whose back is a giant spiral snail shell, plush cushion seat, fantasy biology furniture.",
    },
    {
        "id": "whimsy_geode_table",
        "name": "晶洞茶几",
        "set": "奇匠造物套",
        "slot": "table",
        "scene": "butterfly_house",
        "level": 18,
        "cost": 960,
        "star": 4,
        "rarity": "fine",
        "palette": "amethyst geode slab as tabletop, iron legs, crystal points glowing softly",
        "subject": "A coffee table with amethyst geode crystal slice as the top surface, dark metal legs, magical mineral specimen furniture.",
    },
    {
        "id": "whimsy_ladder_shelf",
        "name": "滑轨书梯",
        "set": "奇匠造物套",
        "slot": "shelf",
        "scene": "butterfly_house",
        "level": 20,
        "cost": 1080,
        "star": 4,
        "rarity": "fine",
        "palette": "rolling library ladder merged with bookshelf, oak rails, colorful blank books",
        "subject": "A tall bookshelf with an attached rolling ladder on rails, blank colorful book spines, inventor library mood.",
    },
    # ── Set 10: 古茶雅集套 ──
    {
        "id": "gucha_tea_boat",
        "name": "茶则舟",
        "set": "古茶雅集套",
        "slot": "table",
        "scene": "tea_house",
        "level": 22,
        "cost": 680,
        "star": 3,
        "rarity": "fine",
        "palette": "bamboo tea boat tray table, gaiwan cup, small tea pitcher",
        "subject": "A low tea service table with bamboo tea boat tray holding gaiwan lidded cup and fairness pitcher, Song-style tea ceremony setup.",
    },
    {
        "id": "gucha_charcoal_brazier",
        "name": "竹风炉",
        "set": "古茶雅集套",
        "slot": "ornament",
        "scene": "tea_house",
        "level": 23,
        "cost": 740,
        "star": 3,
        "rarity": "fine",
        "palette": "bamboo wind furnace brazier, clay kettle on top, gentle charcoal glow",
        "subject": "A ground-standing bamboo charcoal brazier for boiling tea water, clay kettle sitting on top, Tang-Song tea heating prop, not hanging.",
    },
    {
        "id": "gucha_tea_chest",
        "name": "封箱茶仓",
        "set": "古茶雅集套",
        "slot": "shelf",
        "scene": "tea_house",
        "level": 24,
        "cost": 920,
        "star": 4,
        "rarity": "fine",
        "palette": "stacked tea brick chests, paper wraps, wax seal blobs without text",
        "subject": "A storage shelf unit with stacked compressed tea brick packages in paper wraps, wax seals as plain circles, no labels.",
    },
    {
        "id": "gucha_water_jar",
        "name": "陶瓮水缸",
        "set": "古茶雅集套",
        "slot": "ornament",
        "scene": "tea_house",
        "level": 22,
        "cost": 580,
        "star": 2,
        "rarity": "common",
        "palette": "large terracotta water jar, bamboo ladle leaning, ripple water inside",
        "subject": "A large traditional water storage jar with bamboo ladle, used for tea house water, stout rounded silhouette.",
    },
    {
        "id": "gucha_tea_bench",
        "name": "茶寮长凳",
        "set": "古茶雅集套",
        "slot": "ornament",
        "scene": "tea_house",
        "level": 25,
        "cost": 640,
        "star": 2,
        "rarity": "common",
        "palette": "plain pine bench, worn smooth edges, tea stain ring mark",
        "subject": "A simple long tea house bench with honest worn wood, seats three in chibi scale, humble tea lodge seating.",
    },
]

RARITY_CN = {
    "common": "普通",
    "fine": "精良",
    "rare": "稀有",
    "limited": "限定",
}

SLOT_CN = {
    "shelf": "花架",
    "table": "桌台",
    "light": "家电",
    "ornament": "摆件",
    "wallart": "墙饰",
    "garden": "庭院",
}

SCENE_CN = {
    "butterfly_house": "蝴蝶小屋",
    "tea_house": "茶香小院",
    "garden_villa": "花园别墅",
    "forest_treehouse": "橡树小屋",
    "flower_shop": "花店",
}


def build_prompt(item: dict) -> str:
    return (
        f"{STYLE_PREFIX}\n\n"
        f"Color and materials: {item['palette']}.\n\n"
        f"Subject: {item['subject']}\n"
        f"{STYLE_SUFFIX}"
    )


def write_catalog() -> None:
    lines = [
        "# 扩展家具批次 51 — 策划表（创意 / 古风）",
        "",
        "本批侧重 **古风书房、闺阁、宫廷、园林、丹房、江南、节庆、海贸、奇匠、古茶** 等主题；",
        "**不含吊灯 / 壁灯 / 任何悬吊式灯具**（游戏中无法摆放）。",
        "",
        "经济：花愿约 560–1480，星星 2–6；**未写入 DecorationConfig**，待验收后再登记。",
        "",
        "出图：`scripts/gen_furniture_expansion_batch51_nb2.sh` → `../game_assets/huahua/assets/raw/furniture_expansion_batch51/`",
        "",
        "## 套装一览（10 套 × 5 件）",
        "",
    ]
    sets: dict[str, list[dict]] = {}
    for it in ITEMS:
        sets.setdefault(it["set"], []).append(it)

    for set_name, members in sets.items():
        lines.append(f"### {set_name}")
        lines.append("")
        lines.append("| id | 名称 | 槽位 | 场景 | 等级 | 花愿 | 星星 | 稀有度 |")
        lines.append("|---|---|---|---|---:|---:|---:|---|")
        for it in members:
            lines.append(
                f"| `{it['id']}` | {it['name']} | {SLOT_CN[it['slot']]} | {SCENE_CN[it['scene']]} | "
                f"{it['level']} | {it['cost']} | {it['star']} | {RARITY_CN[it['rarity']]} |"
            )
        lines.append("")

    lines.append("## 汇总")
    lines.append("")
    lines.append(f"- 合计：**{len(ITEMS)}** 件")
    lines.append(f"- 花愿区间：**{min(i['cost'] for i in ITEMS)} – {max(i['cost'] for i in ITEMS)}**")
    lines.append(f"- 等级区间：**{min(i['level'] for i in ITEMS)} – {max(i['level'] for i in ITEMS)}**")
    lines.append("- 槽位：**零吊灯**；石灯笼 / 灯杆宫灯均为**落地式**庭院道具")
    lines.append("")

    CATALOG_MD.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    assert len(ITEMS) == 50, f"expected 50 items, got {len(ITEMS)}"
    light_items = [i for i in ITEMS if i["slot"] == "light"]
    assert not light_items, f"batch51 must have no LIGHT slot items: {light_items}"
    PROMPT_DIR.mkdir(parents=True, exist_ok=True)
    for it in ITEMS:
        path = PROMPT_DIR / f"furniture_{it['id']}_nb2_prompt.txt"
        path.write_text(build_prompt(it), encoding="utf-8")
    MANIFEST_JSON.write_text(json.dumps(ITEMS, ensure_ascii=False, indent=2), encoding="utf-8")
    write_catalog()
    print(f"Wrote {len(ITEMS)} prompts to {PROMPT_DIR}")
    print(f"Catalog: {CATALOG_MD}")
    print(f"Manifest: {MANIFEST_JSON}")


if __name__ == "__main__":
    main()
